### ISSUE TITLE
TO-DO (antes do SIIC)

### ISSUE THREAD

**Issue by Honnataj** [Honnataj/projeto_extensao-2024#1]
- [ ] adicionar outros campos do formulário principal (cadastro de requerimentos)
- [ ] adicionar formulários secundários
  - [ ] cadastro de setores
  - [ ] cadastro de responsáveis
  - [ ] cadastro de itens
  - [ ] cadastro de locais de retirada
- [ ] melhorar interface
- [ ] adicionar consulta de dados
